/**
 * MedHub-Backend.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AddLaboratoryDto} from '../model/addLaboratoryDto';
import {LaboratoryDto} from '../model/laboratoryDto';

import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class LaboratoryService {

  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  protected basePath = 'http://localhost:5210';

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   *
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createLaboratory(body?: AddLaboratoryDto, observe?: 'body', reportProgress?: boolean): Observable<LaboratoryDto>;

  public createLaboratory(body?: AddLaboratoryDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LaboratoryDto>>;

  public createLaboratory(body?: AddLaboratoryDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LaboratoryDto>>;

  public createLaboratory(body?: AddLaboratoryDto, observe: any = 'body', reportProgress: boolean = false): Observable<any> {


    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/_*+json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<LaboratoryDto>('post', `${this.basePath}/api/v1/Laboratory`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param laboratoryId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteLaboratory(laboratoryId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;

  public deleteLaboratory(laboratoryId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;

  public deleteLaboratory(laboratoryId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;

  public deleteLaboratory(laboratoryId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (laboratoryId === null || laboratoryId === undefined) {
      throw new Error('Required parameter laboratoryId was null or undefined when calling deleteLaboratory.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>('delete', `${this.basePath}/api/v1/Laboratory/${encodeURIComponent(String(laboratoryId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAllLaboratories(observe?: 'body', reportProgress?: boolean): Observable<Array<LaboratoryDto>>;

  public getAllLaboratories(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LaboratoryDto>>>;

  public getAllLaboratories(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LaboratoryDto>>>;

  public getAllLaboratories(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Array<LaboratoryDto>>('get', `${this.basePath}/api/v1/Laboratory`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param laboratoryId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getLaboratoryById(laboratoryId: number, observe?: 'body', reportProgress?: boolean): Observable<LaboratoryDto>;

  public getLaboratoryById(laboratoryId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LaboratoryDto>>;

  public getLaboratoryById(laboratoryId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LaboratoryDto>>;

  public getLaboratoryById(laboratoryId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (laboratoryId === null || laboratoryId === undefined) {
      throw new Error('Required parameter laboratoryId was null or undefined when calling getLaboratoryById.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<LaboratoryDto>('get', `${this.basePath}/api/v1/Laboratory/${encodeURIComponent(String(laboratoryId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param laboratoryId
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateLaboratory(laboratoryId: number, body?: AddLaboratoryDto, observe?: 'body', reportProgress?: boolean): Observable<LaboratoryDto>;

  public updateLaboratory(laboratoryId: number, body?: AddLaboratoryDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LaboratoryDto>>;

  public updateLaboratory(laboratoryId: number, body?: AddLaboratoryDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LaboratoryDto>>;

  public updateLaboratory(laboratoryId: number, body?: AddLaboratoryDto, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (laboratoryId === null || laboratoryId === undefined) {
      throw new Error('Required parameter laboratoryId was null or undefined when calling updateLaboratory.');
    }


    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/_*+json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<LaboratoryDto>('put', `${this.basePath}/api/v1/Laboratory/${encodeURIComponent(String(laboratoryId))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
