/**
 * MedHub-Backend.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AddTestRequestDto} from '../model/addTestRequestDto';
import {TestRequestDto} from '../model/testRequestDto';
import {TestResultDto} from '../model/testResultDto';
import {TestTypeDto} from '../model/testTypeDto';
import {UpdateTestRequestDto} from '../model/updateTestRequestDto';

import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class TestRequestService {

  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  protected basePath = 'http://localhost:5210';

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   *
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createTestRequest(body?: AddTestRequestDto, observe?: 'body', reportProgress?: boolean): Observable<AddTestRequestDto>;

  public createTestRequest(body?: AddTestRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddTestRequestDto>>;

  public createTestRequest(body?: AddTestRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddTestRequestDto>>;

  public createTestRequest(body?: AddTestRequestDto, observe: any = 'body', reportProgress: boolean = false): Observable<any> {


    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/_*+json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<AddTestRequestDto>('post', `${this.basePath}/api/v1/TestRequest`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param testRequestId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteTestRequest(testRequestId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;

  public deleteTestRequest(testRequestId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;

  public deleteTestRequest(testRequestId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;

  public deleteTestRequest(testRequestId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (testRequestId === null || testRequestId === undefined) {
      throw new Error('Required parameter testRequestId was null or undefined when calling deleteTestRequest.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>('delete', `${this.basePath}/api/v1/TestRequest/${encodeURIComponent(String(testRequestId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param testRequestId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAllResultsOfRequest(testRequestId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<TestResultDto>>;

  public getAllResultsOfRequest(testRequestId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TestResultDto>>>;

  public getAllResultsOfRequest(testRequestId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TestResultDto>>>;

  public getAllResultsOfRequest(testRequestId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (testRequestId === null || testRequestId === undefined) {
      throw new Error('Required parameter testRequestId was null or undefined when calling getAllResultsOfRequest.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Array<TestResultDto>>('get', `${this.basePath}/api/v1/TestRequest/${encodeURIComponent(String(testRequestId))}/results`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAllTestRequests(observe?: 'body', reportProgress?: boolean): Observable<Array<TestRequestDto>>;

  public getAllTestRequests(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TestRequestDto>>>;

  public getAllTestRequests(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TestRequestDto>>>;

  public getAllTestRequests(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Array<TestRequestDto>>('get', `${this.basePath}/api/v1/TestRequest`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param testRequestId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getRemainingTestTypes(testRequestId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<TestTypeDto>>;

  public getRemainingTestTypes(testRequestId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TestTypeDto>>>;

  public getRemainingTestTypes(testRequestId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TestTypeDto>>>;

  public getRemainingTestTypes(testRequestId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (testRequestId === null || testRequestId === undefined) {
      throw new Error('Required parameter testRequestId was null or undefined when calling getRemainingTestTypes.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Array<TestTypeDto>>('get', `${this.basePath}/api/v1/TestRequest/${encodeURIComponent(String(testRequestId))}/remaining`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param testRequestId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTestRequestById(testRequestId: number, observe?: 'body', reportProgress?: boolean): Observable<TestRequestDto>;

  public getTestRequestById(testRequestId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TestRequestDto>>;

  public getTestRequestById(testRequestId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TestRequestDto>>;

  public getTestRequestById(testRequestId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (testRequestId === null || testRequestId === undefined) {
      throw new Error('Required parameter testRequestId was null or undefined when calling getTestRequestById.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<TestRequestDto>('get', `${this.basePath}/api/v1/TestRequest/${encodeURIComponent(String(testRequestId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param testRequestId
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateTestRequest(testRequestId: number, body?: UpdateTestRequestDto, observe?: 'body', reportProgress?: boolean): Observable<TestRequestDto>;

  public updateTestRequest(testRequestId: number, body?: UpdateTestRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TestRequestDto>>;

  public updateTestRequest(testRequestId: number, body?: UpdateTestRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TestRequestDto>>;

  public updateTestRequest(testRequestId: number, body?: UpdateTestRequestDto, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (testRequestId === null || testRequestId === undefined) {
      throw new Error('Required parameter testRequestId was null or undefined when calling updateTestRequest.');
    }


    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain',
      'application/json',
      'text/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'text/json',
      'application/_*+json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<TestRequestDto>('put', `${this.basePath}/api/v1/TestRequest/${encodeURIComponent(String(testRequestId))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

}
