/**
 * MedHub-Backend.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {LaboratoryDto} from './laboratoryDto';
import {TestResultDto} from './testResultDto';
import {TestTypeDto} from './testTypeDto';
import {UserDto} from './userDto';

export interface TestRequestDto {
  id: number;
  requestDate: string;
  patientId: number;
  doctor: UserDto;
  laboratory: LaboratoryDto;
  testTypes: Array<TestTypeDto>;
  testResults: Array<TestResultDto>;
}
