/**
 * MedHub-Backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TestResultDto} from './testResultDto';
import {TestTypeDto} from './testTypeDto';

export interface TestRequestDto {
  id: number;
  requestDate: Date;
  patientId: number;
  doctorId: number;
  testTypes: Array<TestTypeDto>;
  testResults: Array<TestResultDto>;
}
